### ISSUE TITLE
modular ESC

### ISSUE THREAD

**Issue by mkeyno** [jean-michel-gonet/pic18f-bldc-controller.X#35]
Hi, sorry to open ticket for my question , actually I intend to made modular ESC in way that controller + gate driver is separated from Mosfets pcb , hence I could increase module ampere by adding parallel Mosfet in the Mosfets pcb, I really appreciated to have your advise or if you know open HW/SW sources let me know

**Comment by jean-michel-gonet** [comment]
Hi,

- If any of the hardware / software here is of any use for you, please, help yourself.
- About the software, there are two layers:
  - The  low level, switching protocol: This hasn't changed much over years. There are two features here: The switching pattern, which is just standard (never changed it since the beginning) -- The PID engine: I adapted it to the car weight and motor power -- The I2C interface: this I change a lot.
  - The high level, which actually resides in a separated module, a raspberry pi, and communicates with the ESC module via I2C. This is a constant work in progress.
- About the hardware: I'm not a professional Electronics Engineer, so it is probably plenty of bad practices, however it is quite powerful. I measured up to 30A, but I believe it can go beyond. If I were to make it more powerful, I would use a higher voltage instead. Nowadays it is easy to find 6s LiPo, so that would be my preferred option.

After using this module for a couple of years, my I wish it would be of the standard size of ESC modules you can buy in the commerce. Then I could use it with more car models and have more fun.

If your project involves SMD, and can accommodate the standardization of the PCB, I could collaborate with you.

Best regards,
  JM 


P.S: Reopen this issue to answer.
